### PR TITLE
check for and remove empty rows

### PR DESCRIPTION
**Pull request by johnclary**

### CODE REVIEW

**Comment by mattlangan** [comment]
@johnclary what branch do you want them in?

**Comment by johnclary** [comment]
@mattlangan  i dropped the unwanted commits from this branch via rebase. this pr is ready to be merged

**Comment by mattlangan** [comment]
@johnclary also it's nice to proper-case the commit title. just makes for a better reading experience when someone's looking at the logs.

**Comment by johnclary** [comment]
rewritten. thanks.

**Pull request merged**
